### ISSUE TITLE
Generate vertical figure

### ISSUE THREAD

**Issue by arpit15** [Mira-13/figure-gen#3]
Can you suggest some way of generating multiple aligned grids in vertical orientation?

**Comment by pgrit** [comment]
Right now, the best way is to create multiple figures with ```horizontal_figure()```, each having the same width. The key to getting the alignment right is to apply the same paddings and/or title sizes to both.

With the LaTeX backend, this will give you two .pdfs that you can then simply put underneath each other. The .pptx backend will require manual stitching via copy&paste, and the only way of getting it done with .html right now is to extract the code, either manually or with a simple regex.

**Comment by Mira-13** [comment]
We now support horizontal figures that are stacked vertically since 25f9dae57fa69d5ca7bcd0034e12f6117945ee1e with `figure()`. Instead of providing a list of modules - like previously for `horizontal_figure()` -, you need to provide a list of lists. 

`figure()` is also included in our tutorial (at the very end). You might want to run the tutorial locally, as GitHub ignores html/css-styles, which is why the results are not shown correctly.

**Comment by arpit15** [comment]
Thanks! This is a really useful feature.
